# Generated by Django 2.1.2 on 2019-02-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('area', models.CharField(max_length=50)),
            ],
        ),
    ]
