# Generated by Django 2.1.2 on 2019-03-04 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PriceAnalysis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='House',
        ),
    ]
